### ISSUE TITLE
can’t open the file if the filename contains chinese.

### ISSUE THREAD

**Issue by ican0** [ebranlard/pyDatView#55] opened 2020-02-27 11:09 UTC
The pyDatView is wonderful. Thanks for the ebranlard's work.
But there are two bugs, they are both because of the chinese.
1) if the filename contains chinese, then there is an error when open the file. 
![image](https://user-images.githubusercontent.com/15863743/75438761-7f5bab00-5993-11ea-9e32-a5869cc961b7.png)
2) usually the fisrt line in data file is the column name. If the column name contains chinese, then the chinese in  picture  cannot show .
![image](https://user-images.githubusercontent.com/15863743/75439372-9d75db00-5994-11ea-983a-10e5ee3e7382.png)

**Comment by ebranlard** [comment] 2020-02-28 08:52
Thank you for your feedback and for posting this.  Could you maybe enclose
a small example file that reproduces the error?
Thanks a lot!

**Comment by ebranlard** [comment] 2020-02-28 08:54
Also,  can you mention if you clone the repository (and if so which python
version are you using), or, if you downloaded an setup.exe file, which
version are you using? (Also shown in the menu Help of the app). thanks!

**Comment by ican0** [comment] 2020-03-01 11:17
Glad for your reply.
1)the  file "normal.csv" and "normal - 副本.csv" have the same content. The only difference is the file name. You can have a test with them.
2)The versions that I use are pyDatView_v0.1-235-dev_portable.zip and pyDatView_v0.1-238-dev_portable.zip
And I think the key is python‘s features：the python does not support for chinese as well as english.
----------
[example.zip](https://github.com/ebranlard/pyDatView/files/4271689/example.zip)
----------
By the way, there are two style now: the scatter and the line. If you could add the third style "scatter + line", it could be better.
Thanks a lot!

**Comment by ebranlard** [comment] 2020-03-03 03:03
Hi, 

Can you try the latest release version (version 242)? 

Issue 1: Opening files with unicode characters in them. The issue should be fixed now, it seemed to be a [pandas issue](https://stackoverflow.com/questions/33819557/unicodedecodeerror-utf-8-codec-while-reading-a-csv-file). 

Issue 2: Pyplot does not support chinese characters. I fixed this issue, but it requires you to install a font.  What I'm doing is detecting potential special characters in labels, and then applying the font "SimHei" (which seems to be the one people tend to use). For it to work, you need to download the font from [here](https://github.com/StellarCN/scp_zh/blob/master/fonts/SimHei.ttf), and then you can place this file either:
   - at the root of the pyDatView folder (i.e. next to `pyDatView.py`)
   - in your matplotlib data font folder 
If you chose the second option, the script below will indicate you where to put the font file. 
```python 
import os
import matplotlib
fpath = os.path.join(matplotlib.rcParams['datapath'], 'fonts/ttf/SimHei.ttf')
print('Matplotlib data path   : ', matplotlib.rcParams['datapath'])
print('New font file should be: ', fpath)
if os.path.exists(fpath):
    print('[ OK ] Font is found')
else:
    print('[FAIL] Font not found. Add it to the path above. )')
```

Let me know if that works for you.

**Comment by ican0** [comment] 2020-03-03 13:09
Nice work! It works well now.Thanks a lot!

By the way, there are two style now: the scatter and the line. If you could add the third style "scatter + line", it could be better.

**Closed** 2020-03-03 13:11 UTC

**Comment by ebranlard** [comment] 2020-10-21 22:05
Hi @ican0, you can now use "Plain" lines, "different line styles (LS)" or scatter, to plot data. I haven't implemented scatter +line or line + scatter. But I hope to let the users chose their styling in (#52), when I get to it.
