### ISSUE TITLE
Load Bladed output file

### ISSUE THREAD

**Issue by arash7444** [ebranlard/pyDatView#87] opened 2021-02-11 11:05 UTC
Hi Emmanuel,

is it possible to add an option to read Bladed output files too? I can provide a python script to read them and some outputs for NREL 5 MW.
Thanks.

**Comment by ebranlard** [comment] 2021-02-11 18:26
Hi Arash
Thanks, that would be a nice contribution indeed1

I can of course take care of it based on your script, but I can also guide you on the process, this way your contribution shows up on github. 

Most of the work needs to be done on the "weio" repository (https://github.com/ebranlard/weio)

1. A new file format can be added by implementing a subclass of `weio/File.py`, for instance `weio/bladed_input_file.py`. You can use the file `turbsim_file.py` for inspiration. The main functions to implement are `read` and `toDataFrame`. The function `write` is a plus, but not required. 

2.  Once implemented, the fileformat needs to be registered in `weio/__init__.py` by adding an import line at the beginning of this script and adding a line in the function `fileFormats()` of the form `formats.append(FileFormat(BladeInputFile))`

3. If possible you can add a small test to read a small file (with a few time steps and channels). The examples are put in `weio/tests/examples_files` and typically start with the format name.  You can look at the file `weio/tests/test_csv.py` for a small example of test case. 

Once this is added to weio (with a pull request), I can easily add this to pyDatView, it's a matter of pointing the submodule `weio` to the new version. Unfortunately, I'm not sure if you could do this as a pull request. 

That would be the process. Let me know if you are up for it, otherwise, I'll be happy to help or take care of it.

**Comment by arash7444** [comment] 2021-02-11 21:53
Cool, thanks. Sure, I will try to follow steps you wrote above and let you know about the outcome of it ;-)

**Comment by arash7444** [comment] 2021-02-18 14:19
Hi again Emmanuel, 
the script is ready. I made a branch in your weio repository to push the changes there but I don't have permission. 
I can create a mirror of weio in my repository and push them there so you can access them. 
Let me know please how you prefer to proceed.
Thanks.

**Comment by ebranlard** [comment] 2021-02-18 17:40
Hi Arash

Thanks a lot, that's great news! 
Yes, I think the typical process would be to fork weio on your own github, push your branch on your github and do a pull request (if you go to your work of weio, github display a link to do that after you push your branch).
Cheers,

**Comment by arash7444** [comment] 2021-02-20 18:15
Hi Emmanuel, 

Thanks, I did it and created a pull request.
I am not sure if I edited `weio/__init__.py` correctly. Please have a look at it.
I have added some example bladed files and they are binary files. 
I need to detect if the file is binary or ascii. I did not know how to do that so I used a  module, called `binaryornot ` in my script but I removed it here because I thought that if I include a command from that module, the code would crash. So let me know if you have an smart way to detect binary vs ascii without using that module so I can update `bladed_out_file.py`.

Please let me know how it works.

Thanks again.

**Comment by ebranlard** [comment] 2021-03-03 00:30
Thanks a lot for your work on weio, the latest version of pyDatView (0.2-119) should now have the bladed file format.  Let me know if works as intended.

**Comment by arash7444** [comment] 2021-03-03 17:44
cool, it works very well, thank you. I still need to find a better way to read ascii files. I will update it later.
Could you please release an installer executable for this version too?

**Comment by ebranlard** [comment] 2021-03-03 17:55
Sounds good, no problem, feel free to update it whenever you get to it. You can also add a couple of checks to the unittest as well for the ascii file. If you need help to run the tests let me know, I'm happy to help. 
 
The executable are automatically generated, so you should be able to find it under the release tab of pyDatView. 

(on the other hand, and if you cloned the repository, you can get the latest version by doing  `git pull --recurse-submodules`)

**Comment by arash7444** [comment] 2021-03-03 18:04
Nice, thanks. I just found executable file for pyDatView 0.2-119. 
Sure I will add some checks to the unittest for ascii files too in the next update.
Thanks a lot again for your help.

**Comment by ebranlard** [comment] 2021-03-03 18:06
Yes, that should be the latest. 

Great! Thanks again!

**Comment by SimonHH** [comment] 2021-03-03 20:55
Hi,
I was following this issue very interested and was happy to see the Bladed file format added. I tried to open some time series but got errors (IndexError: list index out of range coming from bladed_out_file.py in line 76).
I attached a  ziped sample file that was run with Bladed 4.4. It is reduced to only one % $ pair to keep it simple.

It would be nice if you could check if you can reproduce my error and fix it.

Best regards,
Simon
[demo_a_44.zip](https://github.com/ebranlard/pyDatView/files/6078995/demo_a_44.zip)

**Comment by ebranlard** [comment] 2021-03-03 21:56
Thanks Simon, I had no trouble opening the example files you sent somehow. 

Which platform are you using? If on windows, did you download the setup.exe, if so make sure it's the version 119?
If not on windows, let us know which version of python you are using. 

I can see that Arash used split by tab on line 75. I think a simple `split()` would split by space , tab and newlines and might work  (`temp_2 = temp.split()`). Can you give it a try maybe, or put a couple of print statement to see what's happening?  

Thanks

**Comment by arash7444** [comment] 2021-03-03 22:54
Hi Simon, 
I open it with no problem too.  
Emmanuel is right, make sure that you have the most updated one.
and yes Emmanuel, I agree that line 75 should be corrected. I had similar issue in "line 82" and I will apply the same fixed for line 75 too.

**Comment by ebranlard** [comment] 2021-03-03 23:21
@arash7444  let me know if you can submit a pull request so that the reader can read files delimited by tabs or spaces. 

One thing you can do, is remove the first part of the line, since you already know how many character there is: 
`line = line[6:].strip()` 
I believe a simple "split()" would work most of the times. You can also replace tabs with multiple spaces, e.g. `line.replace('\t', '   ' )`, before doing the splits. This will not work for the signals names, but there, your solution of splitting by multiple space would work.  

Keep me in touch, otherwise I can take care of it at some point.

**Comment by SimonHH** [comment] 2021-03-04 07:38
Hi together,
I double checked on my side and found out, that pydatview tries to read also files with the same name in subfolders. That works as long as the files in the subfolder are readable by themselfes. In my case I had a % $ pair in a subfolder that produced the descibed error. From my checks the error seems to be only given for % $ pairs with 3d data stored in it.
I suggest
- disable reading from subfolders
- enable reading 3d type files
I attach the same run as yesterday but with a subfolder and a not working file in it.

Best regards,
Simon

[demo_a_44_subfolder.zip](https://github.com/ebranlard/pyDatView/files/6081650/demo_a_44_subfolder.zip)

**Comment by arash7444** [comment] 2021-03-04 13:08
Hi Simon,

Thanks for checking it. I see the problem and I will apply the correction now.

**Comment by ebranlard** [comment] 2021-03-04 18:38
Thanks Arash for fixing this, I had some suspicion about the `os.walk`. 

Simon let us know if the latest pyDatView (120) works for you, from what I can see it's able to load your 4 and 15 file. 

Thanks to both of you for your help!

**Comment by SimonHH** [comment] 2021-03-05 09:28
Hi all,
I can confirm that the reading of subfolders is disabled and 3d files are now read correctly.
But unfortunatly i still got errors with other % $ pairs.
I attach a full run of the demo_a sample file with a subfolder exclude.
All files in that subfolder are causing an error.
As far as i can see the followings item are to be resolved:

1. - dimension is different compared to other files (e.g. %37). This is quite difficult to solve. Can PyDatView's main code handle such a inconsistency?
2. - VARIAB names are not always given with 'example sensor name' but with bladed converted abreviations like MXT (e.g. %25)
3. - The same is true sometimes for VARUNIT aswell, although not for the sample files attached. Then it is 'example unit' instead of FL.
4. - FORMAT is sometimes given with n/a

Apart from these items it takes quite long to read a time series because all % $ are read.
As a solution I suggest to only read $ % pairs that are marked in the dialog. That increases speed and reduces errors as not all files show above listed problems. But 2 and 3 should still be fixed in my opinion as relevant % $ pairs contain such nomenclatures.
Let me know if I can further support.

Best regards,
Simon

[demo_a_full.zip](https://github.com/ebranlard/pyDatView/files/6089230/demo_a_full.zip)

**Comment by arash7444** [comment] 2021-03-06 16:50
Hi Simon,

Thanks for you message and good points you mentioned.
I wrote the code based on the result I have from Bladed 4.8 and it was working with those data so I apologize for the crashes and bugs but I am trying my best. I do not understand why such an expensive commercial software is not following a certain structure when it writes an output.

I tried to fix the problem you mentioned so I explain here what I did for those issues:

> dimension is different compared to other files (e.g. %37). This is quite difficult to solve. Can PyDatView's main code handle such a inconsistency?

- _I know that problem so the code will check if the dimension is different with others file, it will skip that file. The solution is to load that file separately from another folder or change "time step" so it has the same size_

> VARIAB names are not always given with 'example sensor name' but with bladed converted abreviations like MXT (e.g. %25)

- _I can see that issue. I tried to solve it by generating some dummy name if the code cannot read VARIAB  names so it will write as Channel 1, Channel 2,....,Channel n. where n is the number found in "DIMENS". 

if we look at demo_a_44.%25 as an example, DIMENS             8          2       1200 so if the code cannot read VARIAB   or it detect something wrong then it would assign channel names with these type of names: Channel 1, Channel 2,... Channel 8_


> The same is true sometimes for VARUNIT aswell, although not for the sample files attached. Then it is 'example unit' instead of FL.

- _for the unit, it does not crash and it would not create dummy unit name but unit name for that file would be wrong ;-)_


> FORMAT is sometimes given with n/a

- _I fixed it and it would read the files the same format as R4 file_


> Apart from these items it takes quite long to read a time series because all % $ are read.

- _I agree that it is too slow but reading a single file is also annoying. The picture below is an example of what happens if user read all % $ as a single file. To be honest I don't know what would be the best solution for it._
- _Emmanuel (@ebranlard), do you have a better solution?  You can change the code to read only a single file, by commenting line 322 and using line 323._

![image](https://user-images.githubusercontent.com/21036995/110214097-4659ee80-7ea3-11eb-8047-55f0bbb0c0d8.png)

**Comment by ebranlard** [comment] 2021-03-06 20:34
Thanks to both of you for the testing and implementation. 

The `toDataFrame` function can return one table, or a dictionary of tables. The "name" of the table can be set as the key of the dictionary, so that this name will appear in pyDatView. 

An approach would be the following:

- If the user drag and drop a project file then all files are read, and concatenated into one table (current behavior). If there are time steps issues, we can return different tables for each consistent sets (all the files with the same time vectors are concatenated together). We will have to give some kind of name to each set. 

- If the user drag and drop % or $ files, then only these files are read. They won't be concatenated into one table. To avoid them being shown as "tab0" etc in pyDatView, we just need the toDataFrame function to give them a meaningful name (the number of the extension? if that number is meaningful, or some kind of name derived from the sensor file). 

Let me know if that would work. For now, I've pushed Arash latest version (121). I'll dive a bit into the code, and see what can be optimized to speed up the reading. 

Thanks again!

**Comment by ebranlard** [comment] 2021-03-07 02:29
Hi both, 

Here's what I've done:

- I've done some cleanup to the reading, trying to optimize it as much as I could, so hopefully it'll be a tiny fit faster
- I've implemented what I suggested above: drag and dropping a PJ will read everything, drag and dropping one or a set of files will only open those. I've used "GENLAB" for the table names. When you open a PJ, you'll get different tables based on the data size. You'll get tables called "Misc" when data have been concatenated. If you'd like to only have one table when loading the PJ, I need to find a way to know which one would be the "main one". I can set it as the one with the most sensors. 
-  I'm adding a "Time" vector as a first sensor. I determine it based on MIN and NSTEP. 
- I've replaced [sec] by [s] (personal choice..), and removed the radial position from the unit. 

If you can give it a try that would be great. I've probably reintroduced some bugs though.. 

I need to add more files for the unittests, I've used the ones from Simon, but I'd prefer if they were slightly smaller.  @SimonHH, could you rerun the case you sent, but for for only 10 time steps for instance? 

Thanks a lot,

Emmanuel

**Comment by SimonHH** [comment] 2021-03-07 12:29
Hi both,

Great work, thank both of you! Behaviour is intuitive now. The ability to only read one fileending (or a selection) but also be able to read all at once if needed is perfect.
Implementation of the "Time" vector, table name from GENLAB, sensor names and units is correct in my view.

The table with most sensors is the one I would in almost all cases be interested in. The others are more for debbing situations. And in these cases it would be fine to open these files seperatly. For me it would thus be fine to just omit tables that are not the standard length. A bonus would be that less file are loaded.
But that is my personal view and it might be contra-intitive for someone else expecting all files to be read.

I tried opening time series from different Bladed versions (4.4 and 4.11). With all files i had at hand no error was given.
I reran the demo_a file with all outputs actived but with only 10 timesteps:
[demo_a_short.zip](https://github.com/ebranlard/pyDatView/files/6097072/demo_a_short.zip)

I found out that there was a further file format not supported till now (see folder exclude in attached zip-file).
It is quite annoying how many different formats there are.

I suggest to skip fileendings that give an error while reading so that formats not discoverd and implemented till now do not produce further errors when loading all fileendings.

A bug that might be introcuded with the latest changes is that the pan mode does not work anymore:
![image](https://user-images.githubusercontent.com/38310787/110238820-00089c00-7f44-11eb-99e2-ef8746cf0475.png)

Best regards,
Simon

**Comment by SimonHH** [comment] 2021-03-07 12:33
Hi both,

**Great work, thank both of you!** Behaviour is intuitive now. The ability to only read one fileending (or a selection) but also be able to read all at once if needed is perfect.
Implementation of the "Time" vector, table name from GENLAB, sensor names and units is correct in my view.

The table with most sensors is the one I would in almost all cases be interested in. The others are more for debbing situations. And in these cases it would be fine to open these files seperatly. For me it would thus be fine to just omit tables that are not the standard length. A bonus would be that less file are loaded.
But that is my personal view and it might be contra-intitive for someone else expecting all files to be read.

I tried opening time series from different Bladed versions (4.4 and 4.11). With all files i had at hand no error was given.
I reran the demo_a file with all outputs actived but with only 10 timesteps:
[demo_a_short.zip](https://github.com/ebranlard/pyDatView/files/6097079/demo_a_short.zip)

I found out that there was a further file format not supported till now (see folder exclude in attached zip-file).
It is quite annoying how many different formats there are.

I suggest to skip fileendings that give an error while reading so that formats not discoverd and implemented till now do not produce further errors when loading all fileendings.

A bug that might be introcuded with the latest changes is that the pan mode does not work anymore:
![image](https://user-images.githubusercontent.com/38310787/110239887-a014f400-7f49-11eb-9f58-8d30342864e4.png)

Best regards,
Simon

**Comment by ebranlard** [comment] 2021-03-07 19:16
Thanks a lot, I'll take care of that and get back to you. 

I'm still unsure as to how I can detect the "main" table, I can definitely eliminate the files whose sensor file don't contain "MIN" and "NSTEP". If there are several files with time outputs of different length (not sure if that could happen), then I guess I will chose the table that has the most time steps, but I'll probably know that at the end.

**Comment by arash7444** [comment] 2021-03-08 15:07
Hi Emmanuel, 

Thanks for the update and fixing the bugs. 
I just found another problem.  It crashes when "SectionList" are string (not numbers) because the code is using "np.around".  
I have attached an example here.  

it crashes in this line:
` SName.append(str(np.around(info['SectionList'][isec],2)) + 'm-' + chan)`

I used `try, except` as a solution and pushed it in the `weio` but I am not sure if it is the smart way ;-)  


[NaN.zip](https://github.com/ebranlard/pyDatView/files/6100263/NaN.zip)

**Comment by ebranlard** [comment] 2021-03-08 17:45
Thanks again Arash, I've now added a case like that in the unittests and included your change. 

Thanks both for your patience, hopefully we are getting there!

**Comment by SimonHH** [comment] 2021-03-08 18:21
Let's see how many versions we have to go...

I ran another test run with multi-member-tower.
And suprise suprise another format apears.
[AXITICK_example.zip](https://github.com/ebranlard/pyDatView/files/6103342/AXITICK_example.zip)

Instead of AXIVAL here AXITICK is used and the station names are given with 'example location' and not with a number anymore.

**Comment by ebranlard** [comment] 2021-03-08 18:49
hahaha, yes, it might take a while. 

I think the latest version (130) should handle these issues, no? 

Here's the sensor names I get with your example: 
![image](https://user-images.githubusercontent.com/1318316/110366991-55a47d80-8004-11eb-92fb-b38c54de6b9b.png)

**Comment by arash7444** [comment] 2021-03-09 15:42
Hi Simon.

yes, that does not work when there are multiple lines for AXITICK or any other section such as VARIAB or VARUNIT. I will try to find more a general solution for it.

**Comment by ebranlard** [comment] 2021-03-09 19:58
I had introduced a hack to attempt to read the next line for VARIAB (based on one of simon's test case). Maybe something similar can be attempted for AXITCK and VARUNIT. Something like, if the next line doesn't start with some keywords, then join the next line with the current line.

**Comment by ebranlard** [comment] 2021-03-19 18:02
@arash7444 let me know if you'll attempt a hack, otherwise I can get a crack at it this weekend. Cheers!

**Comment by ebranlard** [comment] 2021-03-22 00:59
Hi both, 
The latest version (133) should accept 1 or 2 lines for AXITICK, VARIAB and VARUNIT. Let me know if otherfiles give issues.
Cheers,

Emmanuel

**Comment by arash7444** [comment] 2021-03-30 08:52
Hi Emmanuel, 
sorry for late reply. Unfortunately, I did not have time to work on it. Thanks a lot for the update 👍

**Comment by SimonHH** [comment] 2021-03-30 19:45
Hi Emmanuel,
it works smooth now. Thank you.

I believe there is a bug in __init__.py of weio in line 83 and following when the BladedFile format is not the last format in the list above.

For me that is fine as it is no problem to leave the bladed format as the last format and add new formats above but it still might be worth fixing.

**Comment by ebranlard** [comment] 2021-03-31 00:40
Thanks Simon, you are right, there was an issue there, I've now fixed it. Thanks for that!

**Comment by ebranlard** [comment] 2021-04-20 23:22
I'm closing that thread, until you find another file that breaks it :)

**Closed by ebranlard** 2021-04-20 23:22 UTC
